Repository expnt/herald, pull requests merged in 2025-06, with the labels that each got.

#37 feat: support for pre-signed S3 urls
  .ghjk/deno.lock
  .ghjk/lock.json
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  deno.lock
  ghjk.ts
  import_map.json
  src/auth/mod.ts
  src/backends/mod.ts
  src/backends/s3/buckets.ts
  src/backends/s3/mod.ts
  src/backends/s3/objects.ts
  src/backends/swift/buckets.ts
  src/backends/swift/mod.ts
  src/backends/swift/objects.ts
  src/types/api_errors.ts
  src/utils/log.ts
  src/utils/mod.ts
  src/utils/signer.ts
  src/utils/url.ts
  tests/mirror/mod.ts
  tests/s3/sdk/upload_test.ts
  tests/swift/basic/container_test.ts
  tests/swift/basic/copy_object_test.ts
  tests/swift/basic/object_test.ts
  tests/swift/iac/simple_bucket_test/versions.tf
  tools/compose/compose.s3.yml
  tools/compose/compose.swift.yml
  tools/mc.port.ts
  tools/opentofu_ghrel.port.ts
Labels: enhancement

#35 fix: stricter S3 response compliance
  .ghjk/deno.jsonc
  .github/workflows/tests.yml
  .gitignore
  Dockerfile
  deno.lock
  ghjk.ts
  src/backends/mirror.ts
  src/backends/swift/buckets.ts
  src/backends/swift/mod.ts
  src/backends/swift/objects.ts
  src/backends/swift/utils/mod.ts
  src/constants/errors.ts
  src/constants/s3.ts
  src/main.ts
  src/types/api_errors.ts
  src/utils/url.ts
  tests/s3/objects/multipartupload_test.ts
  tests/swift/basic/container_test.ts
  tests/swift/basic/multipartupload_test.ts
  tests/swift/basic/object_test.ts
  tests/swift/iac/simple_bucket_test/versions.tf
  tests/utils/mod.ts
  tools/compose/compose.s3.yml
  utils/file.ts
  utils/s3.ts
Labels: enhancement, bug fix

#41 fix: error propagation
  .github/workflows/tests.yml
  Dockerfile
  deno.jsonc
  deno.lock
  import_map.json
  src/auth/mod.ts
  src/backends/mirror.ts
  src/backends/mod.ts
  src/backends/s3/buckets.ts
  src/backends/s3/mod.ts
  src/backends/s3/objects.ts
  src/backends/swift/auth.ts
  src/backends/swift/buckets.ts
  src/backends/swift/keystone_token_store.ts
  src/backends/swift/mod.ts
  src/backends/swift/objects.ts
  src/backends/swift/utils/mod.ts
  src/backends/types.ts
  src/backends/worker.ts
  src/constants/errors.ts
  src/main.ts
  src/types/api_errors.ts
  src/types/http-exception.ts
  src/types/mod.ts
  src/utils/log.ts
  src/utils/s3.ts
  src/utils/signer.ts
  src/utils/url.ts
  tests/mirror/bucket_test.ts
  tests/mirror/copyobject_test.ts
  tests/mirror/deleteobject_test.ts
  tests/mirror/putobject_test.ts
  tests/utils/mod.ts
Labels: bug fix
